### ISSUE TITLE
Analyzer fails when using CSS snippets with @-rules in description

### ISSUE THREAD

**Issue by web-padawan** [runem/web-component-analyzer#151]
The following code snippet can't be parsed by analyzer:

```md
 * expand the layout to full document height as follows:
 * ```
 * @media screen {
 *   html, body {
 *     height: 100%;
 *   }
 * }
 * ```
```

Output JSON for `description` field looks like this: 
```md
expand the layout to full document height as follows:\n```",
```

See example at vaadin/vaadin-app-layout#149

**Comment by runem** [comment]
Thanks for opening this issue :+1:

It seems like the Typescript parser thinks `@media` is a JSDoc tag. 

[See example at ts-ast-viewer.com](https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbzgYwK4GcYRAUQDYCmIBAdvAL5wBmU2cA5HsDALQGHFn0DcAUKJFiI4AQTBgAMgEMAnhFQwAQlPQE4lGnXoA6APQA3KVIAmwEiyniWeWfNYAjFQR79w0eEjGTbCgLLAADzN1aloQBj1DEzMLKxs5BRYQQLMXAXcI3WMCGAJkVmAIdBYSKX1HKDS3IR1ddCkqAgsoAikWM1UYF15dACpe3jheuAADAB4o03NLMGsfGAA+EbhgdDgpOAB1Ans4AGFsSBJSeDBafWApgHN1uABHVGBkAGt1kmM4VvQZOAB3WTgWDgVxyt2Q2BAEBIg2GMyYyCkMEKJDg8TscEwUFQ+VQLTgxihBG0cAAYtA4PYCJg4C10Kg8DB0AAaOBgQhOQFSZ5qGAACzUVAgeDwEF+ZhuLXBIE4xkRyPQMJWZAg62Q4NQZAAXDDFXAAIzEkwfPlqKVHE6AlUmmkQCDwQj6dhwCBUOAJKDrcTwuVQuAAChUt1MkvgyF5wDwHxdozG9ggxhkSwAlEzdQAmYlmZB4VDZW4XAi-QTwYgwDZlm6-cNhlBQssdUYFovuFhUZgAXnBjqgyyB1rAUhB6zWguFovQ2qGoxGI0VY1LG1KxHbACIm8WV7WyCdV2LjHz29kLsgmnu+SyzMxgFI8Cx0AjCO29Sz1y22zBOxBuyuFoqZ7OhkVABiECgLgABlZBaGFcV1haFQdSnRQfmyKgpHpGAWWtflgCuXl4GjNEFBWNZULMAgPnsH5mDWcFtzIFkpHeQF+VrNxjjIVVGT+ZheRYghFRXOMEwxKChSYEgrk3dAVV9SF7AjNQ-WAAB5cCIIaKQoGAN4PhEd5aEufZeTCAgk34y0hQqNYxWFWthUsVRFSrUhbnvaC8DgXkZlIdBtEQ4YABUVQwHlWJXOjck49zxPFTcOlyEwWU6UYcLwmBNX1AAGLKAFJll9EZ8JAPBliYj4RmEmRexVAgAgHZiTUVIj4CBKh6U8gk0E4eA0vw4dqHE8dJ2Gf9FQAAWIUwNncghXIQXUvJgEqWSqxBFrgLyCFw-DMr1HLcr4KdNvIRVTqnMap0C8MbIjTyQC5MK1BGSKTmWX4oB8j0Yoc+xCGJABJFE+VWFAnCw1isCsrS1jkiAFMIfECGPASp1+KF6FDcTHKJOAAfgUHjhPdB6igH4gQ+ywLMwGREaxRHgg2EZJoo69RJaUhlgeAgyedE0oDFJypzOMwkUkrcovgKQxJJuAQAw4A2TUAcQVuuzKXWKhGnyCj-MAqdxsRGAPQQOMhVaEhKC-Hn4jgFhRBgY3gHsBQ1BSlyURarzA2MT7fh551u1tuGEbUI8nipPWBgN5ASYHIRHBeX2IDAO24BUoOAVMdA2VkCi-n5FEU9IWDfakf2PRDxSkZRhUY7jrT4DLiu04OMgpHIj1BQ9a1m4DrTWgm2Oc8buBSnKLTW7rDvji78lrXH3CfRRCp-SwVPyopO0sBAJMh4boRx4qFg40duh7bb+tZ8GnvWNPnex7KJekV9Cp95HoRXs4i-p87m+LJVqaOsJwApwHGugEU8B7YABECBoQwhiSB-9+yDiAfRGAE0IF2kfhPD09twJIO7hZdeODV4DykJgpBfc8EQUIeSJino2RPGXnLUgqBKHYKwNiXkLAU5ImSAAL3zvguht81D3zoEfSe5D-RQjwD8C46BnaIyrojcOxM9762GONZGFpsxFCaNbKA8QWDULTjgR0nE+SIjBivNQoVjQqn0aofEfsA5nAgFcT60o5QPnkVHMBujOLUN4WAUgFEWBhiYiCD49sSTABaB8D2FkRjUJUmE44xhlgeLCbAH4UTJKRwmkEgimcZCRO8oU2JpIEn52SdaEYRj4jZNoLkmA+TKmqwCToyxpxtIPTJnePIL9zAFJiWneJiSC6uQaSLAZMhwLDORC04ueSUCdKKQbEplpuGhP4cAIRxgKnROETUqZ9TWIjC4WGdJ+zDkrLaR0k5flim9JpFSA5ag4m1KSYXCy7AiAWlBrST5xhiQADkoQn1QPYP64oo66F4ONNAmBsD4EBWQP09BJgxBmHMBIXQ951WLCgGwssABqRgpheGkASz4AQorGDWDS+Y-gggkD9CyglyhVDmQWptTAviSJwHbAwHF0w4jzG6AKssSJkDAlBN2JRUI-R8sGJtd5MBcQonoAAZm0FlA1Fg8BgG8nqFwJ1eDqr6NHTawwAAS7BcmsL5PGFiNjs4DhgGGKktwXoilULwsppi3E9k+L0vWdrEUyqFZ6xEYY9gBoIBnG2shoGhosScVV60NU8XeKKbQcbvW8kzZi44vx9gYB3qWmAWLnGGODdQ+gSYkxHXULwU6vBsjZgHsCEUjhPL8qVLkKAaETxwHtYFXwEh0U9UCoOcFUhiC+CpkOza2KqW4slQS+gmVKXRBIFyuwbbTrkCAA)

<img width="503" alt="Screenshot 2020-03-06 at 11 03 40" src="https://user-images.githubusercontent.com/5372940/76073643-378fe180-5f9a-11ea-886c-78ac31f8d0e5.png">

This would either need to be fixed in the Typescript parser, or I would have to get around this problem by searching for unclosed quotes and collect invalid parsed JSDoc tags into one single description.

Another solution could be to add support for quoting the `@` like this: `\@`. This would be the easiest solution to implement.

A temporary solution for you could be to replace `@` with the `＠`  sign, but I know it's not optimal.

**Comment by web-padawan** [comment]
> Another solution could be to add support for quoting the @ like this: \@. This would be the easiest solution to implement.

Thanks, this looks like a good workaround 👍
