### ISSUE TITLE
Private properties in static properties

### ISSUE THREAD

**Issue by hsablonniere** [runem/web-component-analyzer#47]
Hey @runem,

I use `_propertyName` in my ` static get properties () {}` but it is not filtered out.

Seems like `parseStaticProperties` does not use `isPropNamePublic`.

Can I propose a PR maybe?

**Comment by runem** [comment]
Hi again, thanks for opening this issue and offering your help! :-) 

It’s funny, earlier today I actually encountered this exact bug during testing and fixed it. Right now the fix is locally on my machine together with mixin-support feature. I expected it to be finished and publish today or tomorrow 🎉

**Comment by runem** [comment]
This is fixed in version `0.1.10` which I just published, so I'll close this issue now :-)
